language: node_js
node_js:
  - '0.10'
  - '0.11'
script: make test-coveralls
deploy:
  provider: heroku
  api_key:
    secure: 4cecee06-87ac-4f60-bd9f-d24a691f4160
  app: travisheroku
  on:
    repo: petrovick/node-coveralls
before_install:
  - npm install express
  - npm install express-load
  - npm install body-parser
  - npm install mongoq
  - npm install lcov-parse
  - npm install log-driver
  - npm install request
  - npm install js-yaml
  - npm install ejs
  - npm install mongodb
  - npm install mongoose
  - npm install express-session
  - npm install express-flash
  - npm install moment
  - npm install multer
  - npm install errorhandler
  - npm install cookie-parser
  - npm install sinon
after_install:
  - node server.js